### ISSUE TITLE
`#![deny(clippy::all)]` and recent change to `useless_vec` lint w/ ts-rs causes clippy check to fail

### ISSUE THREAD

**Issue by rye** [frog-pond/ccc-server-next#83]
As documented in Aleph-Alpha/ts-rs#158, it seems that the `ts-rs` crate has some instances of the `useless_vec` clippy lint. I agree that that crate should be updated to fix the root problem (and have forked to `frog-pond/ts-rs` to hopefully start that effort), but in the meantime, our use of `#![deny(clippy::all)]` will cause clippy to fail despite there being nothing we can do here.

I would like to remove the `#![deny(clippy::all)]` for now, then restore it when the clippy lint gets restored to its original behavior. On Nightly (2023-07-30), the lint no longer fires, so this might be one Rust release cycle.

**Comment by drewvolz** [comment]
So it sounds like our options are:
- (a) Remove our instances of `#![deny(clippy::all)]`, or
- (b) Switch over to our fork of `ts-rs`.

and both options will eliminate errors of `useless_vec` when building with the beta toolchain.

I'd be okay with switching over to our maintained fork of the dependency since there has not been an update in 8 months. Otherwise, let's temporarily remove our references.

**Comment by rye** [comment]
I think this was fixed by #86.
