### ISSUE TITLE
[dev only] bonappetit is returning 500 errors

### ISSUE THREAD

**Issue by drewvolz** [frog-pond/ccc-server-next#87]
Prod is working well.
Local development is impacted.

Steps
1. Try to get data from the `api/food` endpoints
2. We are returned a denied message and a 500 error code

```sh
curl -X GET http://localhost:3000/api/food/named/cafe/burton
```

Thoughts

[`drew/useragent-middleware`](https://github.com/frog-pond/ccc-server-next/compare/main...drew/useragent-middleware) to play around with setting a custom User-Agent.

I am unsure if User-Agent is the source of our issue because we've seen `403 Forbidden` when we had the "node"  issue which we resolved via https://github.com/frog-pond/ccc-server/pull/665 (403 vs 500 status)

Error

> **Sorry, you have been blocked.**
> You are unable to access cafebonappetit.com.
>
> This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

<img width="500" alt="bonappetit blocked" src="https://github.com/frog-pond/ccc-server-next/assets/5240843/0ea086d5-48e9-4ffc-850f-15c2ecbac775">

**Comment by rye** [comment]
I can confirm that this is is not specific to IP address. I also get the same result from my home network.

While we're considering addressing this with UA changes, we should also consider being good neighbors. It's possible that we're getting this because we're querying Cloudflare and not supplying an etag, for example — because we don't really support caching at all at the moment.

**Comment by drewvolz** [comment]
Nice, etags are a good addition of things to take into account (in addition to a caching strategy).
